# Auto-generated by corpus_commit.py from 270d912360d1771c
# Binary: HTTPD-GK  Vendor: juniper  Family: unknown
# Generated: 2026-05-17T14:46:35Z

f sym.webauthenticate_user 0 @ 0x40aa7c
f sym.dvpn_username_password_authentication 0 @ 0x40d100
f sym.client_disconnect 0 @ 0x40d668
f sym.dvpn_username_password_authentication_ext 0 @ 0x40def8
f sym.acadia_authenticate_user 0 @ 0x40ebbc
f sym.write_client_config 0 @ 0x41bee8
f sym.delete_sa 0 @ 0x41d6c8
f sym.send_msg_to_gk 0 @ 0x41fdd8
f sym.prepare_client_config 0 @ 0x4204b8
f sym.get_config_by_token 0 @ 0x422800
f sym.get_config_by_username 0 @ 0x423160
f sym.get_client_config_by_username 0 @ 0x4236c8
f sym.clear_user_connections 0 @ 0x424130
f sym.dvpn_clear_users 0 @ 0x426004
f sym.httpd_gk_rebuild_cache 0 @ 0x4268e4
f sym.cache_jlaunchpad 0 @ 0x426e0c
f main 0 @ 0x42ad2c
f sym.remote_access_vpn_process_request 0 @ 0x42f3b0
