# ═══════════════════════════════════════════════════════════════
# IOS Structure Map — auto-generated by ios_struct_mapper.py
# Binary: C1900-UN.BIN
# ═══════════════════════════════════════════════════════════════

af @ 0x819dd960
afn ios_setjmp @ 0x819dd960

# ── Boot call sequence from entry0 ──
af @ 0x819dd960
afn ios_setjmp @ 0x819dd960
af @ 0x819dea84
afn boot_init_exception @ 0x819dea84
af @ 0x819debc0
afn boot_clear_bss @ 0x819debc0
af @ 0x819cd4e8
afn ios_kernel_init @ 0x819cd4e8
af @ 0x810dd284
afn boot_platform_init @ 0x810dd284
af @ 0x81427b1c
afn boot_call_5 @ 0x81427b1c
af @ 0x810de408
afn boot_call_6 @ 0x810de408
af @ 0x819dd900
afn boot_call_7 @ 0x819dd900
af @ 0x81000688
afn boot_call_8 @ 0x81000688
af @ 0x819de3f0
afn boot_call_9 @ 0x819de3f0
af @ 0x819dd900
afn boot_call_10 @ 0x819dd900
af @ 0x81000688
afn boot_call_11 @ 0x81000688
af @ 0x8339096c
afn ios_registry_add_list @ 0x8339096c
af @ 0x83390e68
afn ios_registry_add_case @ 0x83390e68
af @ 0x83392538
afn ios_registry_add_pid_list @ 0x83392538
af @ 0x829857fc
afn http_server @ 0x829857fc
af @ 0x8355d36c
afn snmp_handler @ 0x8355d36c

# ── IOS Type Definitions ──
# IOS heap chunk header (from Phenoelit research + IOS internals)
# Offsets validated against 'show memory' output format strings
td struct ios_chunk_header { uint32_t magic; uint32_t pid; uint32_t check; uint32_t name_ptr; uint32_t next; uint32_t prev; uint32_t size; uint32_t refcount; };

# IOS process structure (partial — fields from 'show process' output)
td struct ios_process { uint32_t next; uint32_t pid; uint32_t name_ptr; uint32_t stack_base; uint32_t stack_size; uint32_t state; uint32_t priority; uint32_t runtime; uint32_t invoked; uint32_t tty; };

# IOS registry entry
td struct ios_registry_entry { uint32_t func_ptr; uint32_t next; uint32_t service_id; uint32_t flags; };

# IOS parser node (CLI command tree)
td struct ios_parser_node { uint32_t token_str; uint32_t help_str; uint32_t handler_func; uint32_t next_sibling; uint32_t first_child; uint32_t flags; };

