#!/usr/bin/env python3
"""
ios_struct_mapper.py — Map Cisco IOS internal structures from a monolithic binary.

Identifies and annotates key IOS infrastructure via string xrefs:
  1. IOS buginf / printf (the debug logging function — highest xref count)
  2. IOS heap allocator functions (malloc, free, chunk_create)
  3. IOS scheduler / process table
  4. IOS registry (function dispatch table)
  5. IOS CLI parser dispatch
  6. GP-relative global table layout
  7. Network protocol handler registration

Emits r2 commands that label these infrastructure functions and define types.

Usage:
    python3 ios_struct_mapper.py <binary> <output.r2> [--json output.json]
"""

import struct, re, sys, os, json
from collections import defaultdict

BINARY = sys.argv[1]
OUTPUT_R2 = sys.argv[2]
OUTPUT_JSON = sys.argv[3] if len(sys.argv) > 3 else None

REAL_BASE = 0x21000000
FILE_OFF  = 0x60
VA_DELTA  = 0x60000000
TEXT_SIZE  = 0x3F58000

def off_to_rva(off): return off - FILE_OFF + REAL_BASE
def rva_to_elfva(rva): return rva + VA_DELTA
def elfva_to_rva(elfva): return elfva - VA_DELTA

def find_xrefs(data, file_offset, max_results=20):
    """Find lui/addiu xrefs to a string at given file offset."""
    rva = off_to_rva(file_offset)
    hi = (rva >> 16) & 0xFFFF
    lo = rva & 0xFFFF
    lui_imm = (hi + 1) & 0xFFFF if lo >= 0x8000 else hi
    results = []
    for i in range(0, TEXT_SIZE, 4):
        off = FILE_OFF + i
        instr = struct.unpack('>I', data[off:off+4])[0]
        if (instr >> 26) & 0x3F != 0x0F: continue
        if (instr & 0xFFFF) != lui_imm: continue
        rt = (instr >> 16) & 0x1F
        for j in range(1, 12):
            noff = off + j*4
            if noff >= len(data) - 4: break
            ni = struct.unpack('>I', data[noff:noff+4])[0]
            if (ni >> 26) & 0x3F == 0x09 and (ni >> 21) & 0x1F == rt and (ni & 0xFFFF) == (lo & 0xFFFF):
                results.append(rva_to_elfva(off_to_rva(off)))
                break
        if len(results) >= max_results:
            break
    return results

def find_prologue(data, elfva):
    """Walk backward from an r2 VA to find function prologue."""
    rva = elfva_to_rva(elfva)
    start_off = rva - REAL_BASE + FILE_OFF
    for back in range(0, 8192, 4):
        off = start_off - back
        if off < FILE_OFF: break
        instr = struct.unpack('>I', data[off:off+4])[0]
        if (instr >> 16) & 0xFFFF == 0x27BD and (instr & 0xFFFF) >= 0x8000:
            return rva_to_elfva(off_to_rva(off))
    return None

def find_string_offset(data, s):
    """Find a null-terminated string in rodata/data sections."""
    needle = s.encode('ascii') + b'\x00'
    idx = data.find(needle, 0x3F58060)  # start from rodata
    if idx < 0:
        idx = data.find(needle, 0x60)  # fallback: search from start
    return idx if idx >= 0 else None

def count_callers(data, func_elfva):
    """Count jal instructions targeting this function."""
    rva = elfva_to_rva(func_elfva)
    # jal target26 = (rva & 0x0FFFFFFF) >> 2
    target26 = (rva & 0x0FFFFFFF) >> 2
    jal_instr = (0x03 << 26) | target26
    jal_bytes = struct.pack('>I', jal_instr)
    count = 0
    pos = FILE_OFF
    while pos < FILE_OFF + TEXT_SIZE:
        idx = data.find(jal_bytes, pos, FILE_OFF + TEXT_SIZE)
        if idx < 0: break
        count += 1
        pos = idx + 4
    return count


def main():
    print(f"Loading {BINARY}...", file=sys.stderr)
    with open(BINARY, 'rb') as f:
        data = f.read()

    findings = {}
    r2_cmds = []

    r2_cmds.append("# ═══════════════════════════════════════════════════════════════")
    r2_cmds.append("# IOS Structure Map — auto-generated by ios_struct_mapper.py")
    r2_cmds.append(f"# Binary: {os.path.basename(BINARY)}")
    r2_cmds.append("# ═══════════════════════════════════════════════════════════════\n")

    # ─── 1. Find ios_buginf (highest-xref function = printf/buginf) ──────
    print("[1/7] Finding ios_buginf...", file=sys.stderr)
    # Strategy: find a function called from >10000 sites — that's buginf
    # We know from analysis it's at 0x8233f100 but let's confirm by
    # finding the function with the most jal references
    # Use a known debug format string to locate it
    candidates = {}
    for test_str in ["bad magic number %lx (should be %lx)", "Total mem = %u, IO mem = %d"]:
        off = find_string_offset(data, test_str)
        if off is None: continue
        refs = find_xrefs(data, off, 5)
        for r in refs:
            func = find_prologue(data, r)
            if func is None: continue
            # Find jal targets from this function
            func_rva = elfva_to_rva(func)
            func_off = func_rva - REAL_BASE + FILE_OFF
            for i in range(0, 2048, 4):
                ioff = func_off + i
                if ioff >= len(data) - 4: break
                instr = struct.unpack('>I', data[ioff:ioff+4])[0]
                if (instr >> 26) & 0x3F == 0x03:  # jal
                    target = ((instr & 0x03FFFFFF) << 2) | 0x80000000
                    if target not in candidates:
                        callers = count_callers(data, target)
                        candidates[target] = callers

    if candidates:
        buginf_addr = max(candidates, key=candidates.get)
        buginf_callers = candidates[buginf_addr]
        print(f"  ios_buginf at 0x{buginf_addr:08x} ({buginf_callers} callers)", file=sys.stderr)
        r2_cmds.append(f"# ios_buginf — IOS debug logging ({buginf_callers} call sites)")
        r2_cmds.append(f"af @ 0x{buginf_addr:08x}")
        r2_cmds.append(f"afn ios_buginf @ 0x{buginf_addr:08x}\n")
        findings['ios_buginf'] = {'addr': f"0x{buginf_addr:08x}", 'callers': buginf_callers}

    # ─── 2. Find ios_setjmp / ios_longjmp ─────────────────────────────────
    print("[2/7] Finding setjmp/longjmp...", file=sys.stderr)
    # setjmp is the first jal from entry point (0x81000000)
    entry_off = FILE_OFF
    for i in range(0, 512, 4):
        instr = struct.unpack('>I', data[entry_off+i:entry_off+i+4])[0]
        if (instr >> 26) & 0x3F == 0x03:
            target = ((instr & 0x03FFFFFF) << 2) | 0x80000000
            r2_cmds.append(f"af @ 0x{target:08x}")
            r2_cmds.append(f"afn ios_setjmp @ 0x{target:08x}")
            findings['ios_setjmp'] = {'addr': f"0x{target:08x}"}
            print(f"  ios_setjmp at 0x{target:08x}", file=sys.stderr)
            break

    # ─── 3. Find GP base and annotate ─────────────────────────────────────
    print("[3/7] Finding GP base...", file=sys.stderr)
    # GP is set early in entry0: lui t0, hi; addiu t0, t0, lo; move gp, t0
    for i in range(0x80, 0x200, 4):
        instr = struct.unpack('>I', data[entry_off+i:entry_off+i+4])[0]
        # Look for: move gp, reg → SPECIAL opcode, funct=0x25 (or), rd=gp(28)
        if (instr & 0xFC00FFFF) == 0x00000025:  # or rd, rs, zero
            rd = (instr >> 11) & 0x1F
            if rd == 28:  # gp
                rs = (instr >> 21) & 0x1F
                # Walk back to find lui for this register
                for j in range(i-4, max(0, i-40), -4):
                    pi = struct.unpack('>I', data[entry_off+j:entry_off+j+4])[0]
                    if (pi >> 26) & 0x3F == 0x0F and ((pi >> 16) & 0x1F) == rs:
                        lui_val = pi & 0xFFFF
                        # Find addiu
                        for k in range(j+4, i, 4):
                            ki = struct.unpack('>I', data[entry_off+k:entry_off+k+4])[0]
                            if (ki >> 26) & 0x3F == 0x09 and ((ki >> 21) & 0x1F) == rs:
                                lo_val = ki & 0xFFFF
                                gp_real = (lui_val << 16) + (lo_val if lo_val < 0x8000 else lo_val - 0x10000)
                                gp_elfva = gp_real + VA_DELTA
                                r2_cmds.append(f"# GP base (global pointer) — IOS global data table")
                                r2_cmds.append(f"f gp_base @ 0x{gp_elfva:08x}")
                                r2_cmds.append(f"# GP real compiled addr: 0x{gp_real:08x}")
                                findings['gp_base'] = {'elfva': f"0x{gp_elfva:08x}", 'real': f"0x{gp_real:08x}"}
                                print(f"  GP base at 0x{gp_elfva:08x} (real 0x{gp_real:08x})", file=sys.stderr)
                                break
                        break
                break

    # ─── 4. Find IOS kernel_init ──────────────────────────────────────────
    print("[4/7] Finding kernel_init and boot sequence...", file=sys.stderr)
    # Walk entry0's jal chain to map the boot sequence
    boot_calls = []
    for i in range(0, 1024, 4):
        instr = struct.unpack('>I', data[entry_off+i:entry_off+i+4])[0]
        if (instr >> 26) & 0x3F == 0x03:
            target = ((instr & 0x03FFFFFF) << 2) | 0x80000000
            boot_calls.append((rva_to_elfva(off_to_rva(entry_off+i)), target))

    r2_cmds.append(f"\n# ── Boot call sequence from entry0 ──")
    for idx, (callsite, target) in enumerate(boot_calls[:15]):
        name = f"boot_call_{idx}"
        if idx == 0: name = "ios_setjmp"
        elif idx == 1: name = "boot_init_exception"
        elif idx == 2: name = "boot_clear_bss"
        elif idx == 3: name = "ios_kernel_init"
        elif idx == 4: name = "boot_platform_init"
        r2_cmds.append(f"af @ 0x{target:08x}")
        r2_cmds.append(f"afn {name} @ 0x{target:08x}")
        findings[name] = {'addr': f"0x{target:08x}", 'call_order': idx}
        print(f"  boot[{idx}] 0x{target:08x} → {name}", file=sys.stderr)

    # ─── 5. Find IOS registry functions ───────────────────────────────────
    print("[5/7] Finding registry dispatch functions...", file=sys.stderr)
    registry_strings = {
        "registry_add_list": "registry_add_list",
        "registry_add_case": "registry_add_case",
        "registry_add_pid_list": "registry_add_pid_list",
    }
    for label, search_str in registry_strings.items():
        off = find_string_offset(data, search_str)
        if off is None: continue
        refs = find_xrefs(data, off, 3)
        for r in refs[:1]:
            func = find_prologue(data, r)
            if func:
                callers = count_callers(data, func)
                r2_cmds.append(f"af @ 0x{func:08x}")
                r2_cmds.append(f"afn ios_{label} @ 0x{func:08x}")
                findings[f"ios_{label}"] = {'addr': f"0x{func:08x}", 'callers': callers}
                print(f"  ios_{label} at 0x{func:08x} ({callers} callers)", file=sys.stderr)

    # ─── 6. Find heap management functions ────────────────────────────────
    print("[6/7] Finding heap/memory functions...", file=sys.stderr)
    heap_strings = {
        "ios_heap_validate": "bad magic number",
        "ios_memory_info": "Total mem = %u",
        "ios_chunk_manager": "Chunk Manager:",
        "ios_malloc_fail_handler": "MALLOC_FAIL",
    }
    for label, search_str in heap_strings.items():
        off = find_string_offset(data, search_str)
        if off is None:
            print(f"  {label}: string not found", file=sys.stderr)
            continue
        refs = find_xrefs(data, off, 3)
        for r in refs[:1]:
            func = find_prologue(data, r)
            if func:
                callers = count_callers(data, func)
                r2_cmds.append(f"af @ 0x{func:08x}")
                r2_cmds.append(f"afn {label} @ 0x{func:08x}")
                findings[label] = {'addr': f"0x{func:08x}", 'callers': callers}
                print(f"  {label} at 0x{func:08x} ({callers} callers)", file=sys.stderr)

    # ─── 7. Find network protocol handlers ────────────────────────────────
    print("[7/7] Finding protocol handler registrations...", file=sys.stderr)
    proto_strings = {
        "smi_handler": "Smart Install",
        "http_server": "HTTP CORE",
        "snmp_handler": "SNMP ENGINE",
        "ike_handler": "ISAKMP",
        "sip_handler": "SIP Session",
        "cwmp_handler": "CWMP Engine",
    }
    for label, search_str in proto_strings.items():
        off = find_string_offset(data, search_str)
        if off is None: continue
        refs = find_xrefs(data, off, 3)
        for r in refs[:1]:
            func = find_prologue(data, r)
            if func:
                r2_cmds.append(f"af @ 0x{func:08x}")
                r2_cmds.append(f"afn {label} @ 0x{func:08x}")
                findings[label] = {'addr': f"0x{func:08x}"}
                print(f"  {label} at 0x{func:08x}", file=sys.stderr)

    # ─── IOS Type Definitions ─────────────────────────────────────────────
    r2_cmds.append("""
# ── IOS Type Definitions ──
# IOS heap chunk header (from Phenoelit research + IOS internals)
# Offsets validated against 'show memory' output format strings
td struct ios_chunk_header { uint32_t magic; uint32_t pid; uint32_t check; uint32_t name_ptr; uint32_t next; uint32_t prev; uint32_t size; uint32_t refcount; };

# IOS process structure (partial — fields from 'show process' output)
td struct ios_process { uint32_t next; uint32_t pid; uint32_t name_ptr; uint32_t stack_base; uint32_t stack_size; uint32_t state; uint32_t priority; uint32_t runtime; uint32_t invoked; uint32_t tty; };

# IOS registry entry
td struct ios_registry_entry { uint32_t func_ptr; uint32_t next; uint32_t service_id; uint32_t flags; };

# IOS parser node (CLI command tree)
td struct ios_parser_node { uint32_t token_str; uint32_t help_str; uint32_t handler_func; uint32_t next_sibling; uint32_t first_child; uint32_t flags; };
""")

    # ─── Write output ─────────────────────────────────────────────────────
    print(f"\nWriting {OUTPUT_R2}...", file=sys.stderr)
    with open(OUTPUT_R2, 'w') as f:
        f.write('\n'.join(r2_cmds) + '\n')

    if OUTPUT_JSON:
        print(f"Writing {OUTPUT_JSON}...", file=sys.stderr)
        with open(OUTPUT_JSON, 'w') as f:
            json.dump({
                'binary': os.path.basename(BINARY),
                'gp_base': findings.get('gp_base', {}),
                'structures': findings,
            }, f, indent=2)

    print(f"\nMapped {len(findings)} IOS structures.", file=sys.stderr)


if __name__ == '__main__':
    main()
