# Auto-generated by corpus_commit.py from 51f15dfdfd2ae0ae
# Binary: do_update  Vendor: lt  Family: unknown
# Generated: 2026-05-27T15:57:52Z

f sym.imp.memcpy 0 @ 0x401970
f sym.imp.popen 0 @ 0x401ad0
f sym.imp.recvfrom 0 @ 0x401af0
f sym.imp.recv 0 @ 0x401be0
f sym.imp.strcpy 0 @ 0x401d20
f sym.imp.read 0 @ 0x401d50
f sym.imp.fgets 0 @ 0x401e80
