#!/usr/bin/env python3
"""prune-session-zsigs.py — Remove unnamed (fcn./sub.) entries from session .zsig files.

Session zsigs generated by rasign2 before function renaming contain many
anonymous entries (fcn.XXXXXXXX, sub.XXXXXXXX).  When loaded via `zo` during
analysis, these generate spurious rename events that hide real named matches.

This tool rebuilds each low-quality session zsig retaining only entries whose
name does not start with 'fcn.' or 'sub.', then updates zigns/sessions/index.json.

Usage:
    # Prune all sessions below 80% named quality:
    python3 tool/prune-session-zsigs.py

    # Prune specific files:
    python3 tool/prune-session-zsigs.py --keys de2cc34b9686e5da 8073dc82fc3f4caa

    # Dry-run: show what would be pruned without modifying files:
    python3 tool/prune-session-zsigs.py --dry-run

    # Merge duplicate-source pairs: BASE absorbs ABSORB, ABSORB is deleted.
    # BASE is the larger/preferred zsig; ABSORB is the one to fold in.
    python3 tool/prune-session-zsigs.py --merge BASE1:ABSORB1 --merge BASE2:ABSORB2

    # Override quality threshold:
    python3 tool/prune-session-zsigs.py --threshold 90

Requirements:
    r2pipe  (pip install r2pipe)
"""

import argparse
import json
import os
import subprocess
import sys
import tempfile
import shutil

try:
    import r2pipe
except ImportError:
    sys.exit("r2pipe not installed: pip install r2pipe")

R2DIR        = os.environ.get("R2DIR") or os.path.expanduser("~/.local/share/radare2")
SESSIONS_DIR = os.path.join(R2DIR, "zigns", "sessions")
INDEX_PATH   = os.path.join(SESSIONS_DIR, "index.json")

DEFAULT_THRESHOLD = 80   # prune any session below this % named


# ── helpers ───────────────────────────────────────────────────────────────────

def read_zsig_entries(zsig_path):
    """Return list of function names found in a binary SDB .zsig via strings(1)."""
    result = subprocess.run(["strings", zsig_path], capture_output=True, text=True)
    entries = []
    for line in result.stdout.splitlines():
        if line.startswith("zign|"):
            parts = line.split("|", 3)
            if len(parts) >= 3:
                entries.append(parts[2])
    return entries


def rebuild_zsig(zsig_path, names_to_keep, dry_run=False):
    """Rebuild a .zsig retaining only entries in names_to_keep.

    Strategy:
      1. Load the existing .zsig with `zo` and dump all entries as JSON (`zj`)
      2. Filter to only the named entries
      3. Re-create in a fresh r2 session using `za name b <bytes> m <mask>`
      4. Save with `zos`

    This round-trips through r2's JSON representation so all fields
    (bytes, mask, graph, refs) are preserved exactly as they were stored.
    Returns (kept_count, removed_count).
    """
    import json as _json

    # Step 1: dump all entries from the existing zsig
    r2_read = r2pipe.open("malloc://1", flags=["-e", "scr.color=0", "-2"])
    r2_read.cmd(f"zo {zsig_path}")
    zj_raw = r2_read.cmd("zj")
    r2_read.quit()

    if not zj_raw.strip():
        return 0, 0

    all_entries  = _json.loads(zj_raw)
    keep_set     = set(names_to_keep)
    keep_entries = [e for e in all_entries if e.get("name") in keep_set]
    removed      = len(all_entries) - len(keep_entries)

    if not removed:
        return len(all_entries), 0

    if dry_run:
        return len(keep_entries), removed

    # Step 2: rebuild in a fresh r2 session
    r2_write = r2pipe.open("malloc://1", flags=["-e", "scr.color=0", "-2"])
    for entry in keep_entries:
        name  = entry["name"].replace('"', '\\"')
        byt   = entry.get("bytes", "")
        msk   = entry.get("mask", "")
        if not byt:
            continue
        r2_write.cmd(f'za "{name}" b {byt}')
        if msk:
            r2_write.cmd(f'za "{name}" m {msk}')

    # Step 3: save atomically
    tmp = zsig_path + ".tmp"
    r2_write.cmd(f"zos {tmp}")
    r2_write.quit()

    if os.path.exists(tmp) and os.path.getsize(tmp) > 0:
        shutil.move(tmp, zsig_path)
    elif os.path.exists(tmp):
        os.unlink(tmp)
        print(f"  WARNING: rebuilt zsig is empty — original kept", file=sys.stderr)
        return len(keep_entries), 0

    return len(keep_entries), removed


def update_index(key, total, named):
    """Refresh the function_count and named_pct in index.json for a given key."""
    if not os.path.exists(INDEX_PATH):
        return
    with open(INDEX_PATH) as fh:
        index = json.load(fh)
    if key not in index:
        return
    pct = int(named * 100 / total) if total > 0 else 0
    index[key]["function_count"] = total
    index[key]["named_pct"]      = pct
    with open(INDEX_PATH, "w") as fh:
        json.dump(index, fh, indent=2, sort_keys=True)
        fh.write("\n")


# ── merge helpers ────────────────────────────────────────────────────────────

def merge_zsig_pair(base_key, absorb_key, sessions_dir, index, dry_run=False):
    """Merge ABSORB into BASE: load both into r2, save to base path, remove absorb.

    BASE wins on name collisions (loaded second so its entries overwrite ABSORB's).
    Returns (merged_count, absorb_count) or (0, 0) on error.
    """
    base_path   = os.path.join(sessions_dir, f"{base_key}.zsig")
    absorb_path = os.path.join(sessions_dir, f"{absorb_key}.zsig")

    for path, label in ((base_path, "base"), (absorb_path, "absorb")):
        if not os.path.exists(path):
            print(f"  ERROR: {label} zsig not found: {path}", file=sys.stderr)
            return 0, 0

    absorb_entries = read_zsig_entries(absorb_path)
    base_entries   = read_zsig_entries(base_path)

    if dry_run:
        all_names = set(absorb_entries) | set(base_entries)
        print(f"  [dry-run] would merge {len(absorb_entries)} absorb sigs into"
              f" {len(base_entries)} base sigs -> ~{len(all_names)} unique")
        return len(all_names), len(absorb_entries)

    # Load absorb first, then base (base wins on name collision)
    r2 = r2pipe.open("malloc://1", flags=["-e", "scr.color=0", "-2"])
    r2.cmd(f"zo {absorb_path}")
    r2.cmd(f"zo {base_path}")
    try:
        merged_count = int(r2.cmd("z~?").strip())
    except ValueError:
        merged_count = 0

    tmp = base_path + ".merge_tmp"
    r2.cmd(f"zos {tmp}")
    r2.quit()

    if not os.path.exists(tmp) or os.path.getsize(tmp) == 0:
        print(f"  ERROR: merged zsig is empty -- aborting", file=sys.stderr)
        if os.path.exists(tmp):
            os.unlink(tmp)
        return 0, 0

    shutil.move(tmp, base_path)
    os.unlink(absorb_path)

    # Count actual function entries via strings(1) -- z~? overcounts SDB record lines
    import subprocess as _sp
    result = _sp.run(["strings", base_path], capture_output=True, text=True)
    merged_count = sum(1 for l in result.stdout.splitlines() if l.startswith("zign|"))

    # Update index
    if absorb_key in index:
        del index[absorb_key]
    if base_key in index:
        index[base_key]["entry_count"] = merged_count
        combined = list(dict.fromkeys(
            index[base_key].get("sample_names", []) + absorb_entries[:3]
        ))[:5]
        index[base_key]["sample_names"] = combined
        index[base_key]["note"] = (
            index[base_key].get("note", "") +
            f" | merged absorb key {absorb_key} ({len(absorb_entries)} sigs)"
        )

    return merged_count, len(absorb_entries)


# ── main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Remove fcn./sub. entries from low-quality session zsigs"
    )
    ap.add_argument("--r2dir",     default=None,
                    help="Override R2DIR (default: R2DIR env var or ~/.local/share/radare2)")
    ap.add_argument("--keys",      nargs="*", default=None,
                    help="16-char hash prefixes to prune (default: all below threshold)")
    ap.add_argument("--threshold", type=int, default=DEFAULT_THRESHOLD,
                    help=f"Prune sessions below this %% named quality (default {DEFAULT_THRESHOLD})")
    ap.add_argument("--dry-run",   action="store_true",
                    help="Show what would change without modifying files")
    ap.add_argument("--all",       action="store_true",
                    help="Prune ALL sessions regardless of threshold (use carefully)")
    ap.add_argument("--merge",     nargs="+", metavar="BASE:ABSORB", default=None,
                    help="Merge pairs: BASE absorbs ABSORB, ABSORB is deleted. "
                         "Repeat for multiple pairs, e.g. --merge A:B C:D")
    args = ap.parse_args()

    # Allow --r2dir to override the module-level R2DIR / SESSIONS_DIR / INDEX_PATH
    global R2DIR, SESSIONS_DIR, INDEX_PATH
    if args.r2dir:
        R2DIR = os.path.abspath(args.r2dir)
        SESSIONS_DIR = os.path.join(R2DIR, "zigns", "sessions")
        INDEX_PATH   = os.path.join(SESSIONS_DIR, "index.json")

    if not os.path.exists(INDEX_PATH):
        sys.exit(f"ERROR: session index not found: {INDEX_PATH}\nRun corpus_commit first.")

    with open(INDEX_PATH) as fh:
        index = json.load(fh)

    # ── merge mode ─────────────────────────────────────────────────────
    if args.merge:
        pairs = []
        for spec in args.merge:
            if ':' not in spec:
                sys.exit(f"ERROR: --merge expects BASE:ABSORB pairs, got {spec!r}")
            base_k, absorb_k = spec.split(':', 1)
            pairs.append((base_k.strip(), absorb_k.strip()))

        ok = True
        for base_k, absorb_k in pairs:
            for k in (base_k, absorb_k):
                if k not in index:
                    print(f"WARNING: key {k!r} not in index.json", file=sys.stderr)
            merged, absorbed = merge_zsig_pair(
                base_k, absorb_k, SESSIONS_DIR, index, dry_run=args.dry_run)
            if merged == 0 and absorbed == 0:
                print(f"  FAILED: {base_k} <- {absorb_k}")
                ok = False
            else:
                print(f"  {'[dry-run] ' if args.dry_run else ''}merged: "
                      f"{base_k} <- {absorb_k}  ({merged} sigs, absorbed {absorbed})")

        if not args.dry_run and ok:
            with open(INDEX_PATH, 'w') as fh:
                json.dump(index, fh, indent=2, sort_keys=True)
                fh.write('\n')
            print(f"\nindex.json updated ({len(pairs)} pair(s) merged).")
        return

    # ── prune mode (default) ─────────────────────────────────────────────
    # Determine which keys to process
    if args.keys:
        targets = {k: index[k] for k in args.keys if k in index}
        missing = set(args.keys) - set(targets)
        if missing:
            print(f"WARNING: not in index: {missing}", file=sys.stderr)
    elif args.all:
        targets = index
    else:
        targets = {k: v for k, v in index.items()
                   if v.get("named_pct", 100) < args.threshold}

    if not targets:
        print(f"No sessions below {args.threshold}% quality threshold.")
        return

    print(f"{'DRY RUN — ' if args.dry_run else ''}Processing {len(targets)} session(s):\n")
    print(f"  {'Key':20} {'Binary':30} {'Before':10} {'After':10} {'Removed'}")
    print(f"  {'─'*20} {'─'*30} {'─'*10} {'─'*10} {'─'*7}")

    for key, entry in sorted(targets.items()):
        zsig_path = os.path.join(SESSIONS_DIR, f"{key}.zsig")
        if not os.path.exists(zsig_path):
            print(f"  {key:20} MISSING ZSIG FILE — skipping")
            continue

        all_names    = read_zsig_entries(zsig_path)
        named_before = [n for n in all_names
                        if not n.startswith("fcn.") and not n.startswith("sub.")]
        total_before = len(all_names)

        kept, removed = rebuild_zsig(zsig_path, named_before, dry_run=args.dry_run)

        binary  = entry.get("binary", "?")[:28]
        pct_aft = int(kept * 100 / max(kept, 1)) if kept else 0
        print(f"  {key:20} {binary:30} {total_before:<10} {kept:<10} {removed}")

        if not args.dry_run and removed > 0:
            update_index(key, kept, kept)

    if args.dry_run:
        print("\n  (dry-run: no files modified)")


if __name__ == "__main__":
    main()
