# autel-aarch64.r2 — Autel EVO 2 AArch64 Android Analysis Profile
#
# Targets:
#   Autel EVO 2 Advanced — Air Node (ModelC-A) and Remote Controller
#   Firmware: V1.4.4 (V1.1.2.8 build 2025-01-13)
#   SoC: Leadcore LC1881 (AArch64, Android 7/8 AOSP)
#
# Key binaries (all AArch64 LE, stripped, Android bionic):
#   transmit        (3.4 MB C++) — drone C2 protocol bridge: MAVLink ↔ DUPC ↔ LTE P2P
#   UpgradeService  (~1 MB C++)  — OTA firmware updater, 27+ system() sinks
#   libdjiw.so      (shared lib) — DUPC protocol implementation, 5 cmd injection sinks
#   clisrv          (Wi-Fi ACU)  — DUPC Wi-Fi command dispatcher
#
# Selected automatically when:
#   vendor slug = "autel"  AND  arch = aarch64  AND  bits = 64
# See: scripts/aether_r2profile.py _VENDOR_PROFILE_MAP ("aarch64","64","autel")
#
# Usage:
#   r2 -i profiles/autel-aarch64.r2 transmit
#   r2 -i profiles/autel-aarch64.r2 UpgradeService

# ── Architecture: AArch64 LE, Android bionic ─────────────────────────────────
e asm.arch=arm
e asm.bits=64
e cfg.bigendian=false

# PLT stub resolution (critical for stripped Android binaries)
e bin.plt.resolve=true
e anal.jmp.indir=true       ; # BR Xn indirect jumps (C++ vtable dispatch)
e anal.calls=true

# ── Analysis tuning ───────────────────────────────────────────────────────────
e anal.hasnext=true
e anal.jmp.tbl=true         ; # C++ vtable dispatch tables
e anal.strings=true
e anal.datarefs=true
e anal.limits=false

# C++ demangling (Itanium ABI — Android NDK default)
e bin.demangle=true
e anal.cpp.abi=itanium

# ── Zignature settings ────────────────────────────────────────────────────────
e zign.graph=true
e zign.refs=true
# Lower matching thresholds — default mincc=10 kills simple functions (1-3 BBs)
e zign.mincc=1
e zign.minsz=4

# ── Visual ────────────────────────────────────────────────────────────────────
e asm.describe=true
e asm.comments=true
e asm.cmt.col=60

# ── Type definitions ──────────────────────────────────────────────────────────
e dir.types=~/.local/share/radare2/types
to libc/functions.h
to libc/socket.h
to libc/errno.h
to libc/signal.h
to android/jni.h
to android/functions.h
to android/log.h

# ── Zignatures: Android NDK arm64-v8a ────────────────────────────────────────
# Generated by: tool/generate-ndk-zsig.py --arch arm64-v8a
# Covers: bionic libc.a, libm.a, libc++_static.a
zo android/arm64-v8a/ndk-r27c.zsig

# ── Magic scans ───────────────────────────────────────────────────────────────
/m /root/.local/share/radare2/magic/crypto_tables.magic
/m /root/.local/share/radare2/magic/proto_fingerprint.magic

# ── Known symbols — transmit (binary 6351a647, EVO 2 V1.4.4) ─────────────────
# Source: vault/Findings/CMD_INJECTION_6351a647_transmit.md (2026-04-28 session)
# transmit bridges MAVLink (from flight controller) ↔ DUPC (C2 protocol) ↔ LTE radio.
# All addresses are AArch64 VAs in stripped PIE binary.

f sym.transmit_SetSystemDateAndTime    @ 0x0006aaa4  ; # sprintf → system() SINK #1
f sym.transmit_set_sys_datetime_mavlnk @ 0x0006ab44  ; # JSON parser → sink bridge
f sym.transmit_handle_ground_msg       @ 0x0002b048  ; # main ground C2 dispatcher
f sym.transmit_handle_airplane_msg     @ 0x0000e780  ; # main air C2 dispatcher
f sym.transmit_my_system               @ 0x00097bc0  ; # printf-like system() wrapper
f sym.transmit_EncryptMsg_STUB         @ 0x000b6348  ; # NO-OP stub — returns 0 (no crypto)
f sym.transmit_GetEncryptKey           @ 0x000b6308  ; # returns _obj.EncryptKey (16-bit)
f sym.transmit_write_key_to_file       @ 0x00041d48  ; # writes key to .key.txt
# Inject via: ground message JSON → SetSystemDateAndTime command → system(buf)

# ── Known symbols — UpgradeService (binary 7eff65ef, EVO 2 V1.4.4) ───────────
# Source: vault/Findings/CMD_INJECTION_7eff65ef_UpgradeService.md (2026-04-28 session)
# 27 system() calls through runSystem() + 6 direct. PATH_TRAVERSAL. No firmware signing.

f sym.upgrade_runSystem              @ 0x00007238  ; # core: system() wrapper in CUpgradeUtils.cpp
f sym.upgrade_mkdir_p_injection      @ 0x00007368  ; # sprintf → "mkdir -p <path>" → system()
f sym.upgrade_rm_rf_injection        @ 0x000073d8  ; # sprintf → "rm -rf <path>" → system()
f sym.upgrade_rm_two_paths           @ 0x000074b8  ; # sprintf → "rm -rf <p1> <p2>" → system()
f sym.upgrade_mv_injection           @ 0x00012588  ; # sprintf → "mv <src> <dst>" → system()
f sym.upgrade_cp_to_ota              @ 0x00012c24  ; # sprintf → "cp <src> /data/ota/..." → system()
f sym.upgrade_echo_to_direct         @ 0x00013040  ; # sprintf → "echo <data> > /data/direct..." → system()
f sym.upgrade_direct_system_1        @ 0x0000e8e0  ; # direct system() call (unknown function)
f sym.upgrade_sprintf_system         @ 0x00011640  ; # sprintf → system() pattern

# ── Attack surface summary ────────────────────────────────────────────────────
#
# transmit — Command injection via ground C2 messages:
#   Network:    LTE P2P (drone ↔ controller) or direct Wi-Fi (192.168.1.1)
#   Auth:       Wi-Fi PSK "1234567890" (hardcoded, publicly known)
#               LTE P2P uses device-specific key (extractable from firmware)
#   Entry:      Ground message → JSON parse → SetSystemDateAndTime handler
#   Sink:       snprintf(buf, ..., datetime_str) → system(buf)
#   Crypto:     EncryptMsg() is a NO-OP stub — no message authentication
#
# UpgradeService — Pre-auth firmware update with command injection:
#   Network:    TCP (telnet-accessible), SD card, USB OTA
#   Auth:       Pre-auth (network access to drone or USB)
#   Entry:      OTA update path → CUpgradeUtils methods → runSystem()
#   Sinks:      27 system() calls via runSystem() + 6 direct
#   Vuln2:      PATH_TRAVERSAL in firmware image extraction (no path sanitization)
#   Vuln3:      No firmware signature verification (no PKCS7 / RSA check)
#
# libdjiw.so — 5 additional cmd injection sinks in DUPC Wi-Fi protocol:
#   Source: vault/Findings/CMD_INJECTION_1048cbf5_libdjiw.md
#   Entry:  DUPC packet → libdjiw dispatch → 5× system() calls
#   Auth:   Wi-Fi PSK
#
# Mitigations:
#   transmit:       NO stack canary, NO PIE (fixed addresses)
#   UpgradeService: NO canary, PIE (addresses randomised), Android ASLR active
#   libdjiw.so:     Shared lib — loaded into transmit/clisrv address space

# ── Analysis strategy for large C++ binaries ─────────────────────────────────
# transmit is 3.4 MB — avoid aaa, use targeted analysis:
#
#   aa                                  ; # basic analysis (~30 sec)
#   aaef                                ; # PLT stub rename
#   axt @ sym.imp.system               ; # find all system() callers
#   iz~system,popen,exec,cmd,command    ; # locate format strings near sinks
#   s sym.transmit_SetSystemDateAndTime ; pdg   ; # decompile injection point
#   iz~SetSystemDateAndTime,datetime    ; # confirm command string template
#
# UpgradeService:
#   aa ; aaef
#   axt @ sym.imp.system               ; # 6 direct + trace to runSystem callers
#   s sym.upgrade_runSystem ; pdg      ; # confirm system() call + arg construction
#   iz~mkdir,rm -rf,mv ,cp ,echo ,ota  ; # confirm command templates

echo "Autel EVO 2 AArch64 Android profile loaded."
echo "Key binaries: transmit (3.4MB, pre-auth MAVLink→system()), UpgradeService (27 sinks)"
echo "NDK zsigs: zo zigns/android/arm64-v8a/ndk-r27c.zsig"
echo "Refs: CMD_INJECTION_6351a647_transmit, CMD_INJECTION_7eff65ef_UpgradeService"
