# Juniper JunOS SRX — KMD and related daemons
# Discovered from junos-srxsme-21.3R1.9 (blob f7cfe8cc...)
# Architecture: MIPS64 rel2 (32-bit mode), big-endian, FreeBSD-based
#
# This profile applies to: KMD, HTTPD-GK, and other JunOS MIPS daemons
# that link against the QuickSec/SafeNet IPsec toolkit.

e asm.arch=mips
e asm.bits=32
e cfg.bigendian=true

# JunOS uses n32 calling convention (MIPS)
e anal.cc=n32

# Load Juniper-specific types
e dir.types=~/.local/share/radare2/types
to libc/functions.h
to libc/socket.h
to libc/signal.h
to juniper/srx_httpd_gk.h
to openssl/ssl.h
to openssl/crypto.h

# Load Juniper-specific zignatures (3032 named functions from KMD, 48-byte MIPS byte+mask sigs)
# Generated by: python3 tool/generate-juniper-zsig.py zigns/juniper/junos-kmd-21.3-sigdb.json
# Zignature matching thresholds
e zign.graph=true
e zign.refs=true
e zign.mincc=1
e zign.minsz=4
zo juniper/junos-kmd-21.3.zsig
