# Auto-generated by corpus_commit.py from e1783cf8e45416c7
# Binary: user_v5_catapult.project  Vendor: spacex  Family: unknown
# Generated: 2026-09-25T16:38:12Z

f sym.imp.__deregister_frame_info 16 @ 0x69210
f sym.imp.__register_frame_info 16 @ 0x69220
f sym.imp.__cxa_finalize 16 @ 0x69230
f sym.imp.__stack_chk_fail 16 @ 0x69240
f sym.imp.memset 16 @ 0x69250
f entry0 48 @ 0x69260
f entry.fini0 96 @ 0x692cc
f entry.init0 48 @ 0x6932c
f sym.controlcode_get_file_coverage 8 @ 0x6aac0
f sym.controlcode_set_trace_buffer 93428 @ 0x6aad0
f sym.controlcode_reset_storage 56 @ 0x6adb0
f sym.controlcode_init_runtime 712 @ 0x6adf0
f sym.controlcode_init_assignment_data 8 @ 0x6b0c0
f sym.controlcode_execute 4536 @ 0x7fde0
