# Auto-generated by corpus_commit.py from 8a3f89fbdecff5fb
# Binary: user_v1.project  Vendor: spacex  Family: unknown
# Generated: 2026-09-25T16:38:04Z

f sym.imp.__deregister_frame_info 16 @ 0x69750
f sym.imp.__register_frame_info 16 @ 0x69760
f sym.imp.__cxa_finalize 16 @ 0x69770
f sym.imp.__stack_chk_fail 16 @ 0x69780
f sym.imp.memset 16 @ 0x69790
f entry0 48 @ 0x697a0
f entry.fini0 96 @ 0x6980c
f entry.init0 48 @ 0x6986c
f sym.controlcode_get_file_coverage 8 @ 0x6b000
f sym.controlcode_set_trace_buffer 93572 @ 0x6b010
f sym.controlcode_reset_storage 56 @ 0x6b2f0
f sym.controlcode_init_runtime 712 @ 0x6b330
f sym.controlcode_init_assignment_data 8 @ 0x6b600
f sym.controlcode_execute 4536 @ 0x803c0
