# Auto-generated by corpus_commit.py from e4346034ab561b68
# Binary: user_mmut.project  Vendor: spacex  Family: unknown
# Generated: 2026-05-10T01:18:24Z

f sym.imp.__deregister_frame_info 16 @ 0x64300
f sym.imp.__register_frame_info 16 @ 0x64310
f sym.imp.__cxa_finalize 16 @ 0x64320
f sym.imp.__stack_chk_fail 16 @ 0x64330
f sym.imp.memset 16 @ 0x64340
f entry0 48 @ 0x64350
f entry.fini0 96 @ 0x643bc
f entry.init0 48 @ 0x6441c
f sym.controlcode_get_file_coverage 8 @ 0x65bb0
f sym.controlcode_set_trace_buffer 86516 @ 0x65bc0
f sym.controlcode_reset_storage 56 @ 0x65e80
f sym.controlcode_init_runtime 708 @ 0x65ec0
f sym.controlcode_init_assignment_data 8 @ 0x66190
f sym.controlcode_execute 4448 @ 0x79440
