# Auto-generated by corpus_commit.py from 7e2d32ce217d1106
# Binary: user_v4_1beam.project  Vendor: spacex  Family: unknown
# Generated: 2026-09-25T16:38:09Z

f sym.imp.__deregister_frame_info 16 @ 0x6b050
f sym.imp.__register_frame_info 16 @ 0x6b060
f sym.imp.__cxa_finalize 16 @ 0x6b070
f sym.imp.__stack_chk_fail 16 @ 0x6b080
f sym.imp.memset 16 @ 0x6b090
f entry0 48 @ 0x6b0a0
f entry.fini0 96 @ 0x6b10c
f entry.init0 48 @ 0x6b16c
f sym.controlcode_get_file_coverage 8 @ 0x6db30
f sym.controlcode_set_trace_buffer 91012 @ 0x6db40
f sym.controlcode_reset_storage 56 @ 0x6de40
f sym.controlcode_init_runtime 708 @ 0x6de80
f sym.controlcode_init_assignment_data 8 @ 0x6e150
f sym.controlcode_execute 4540 @ 0x824e0
