# Auto-generated by corpus_commit.py from 995ccdddb4d8308d
# Binary: user_v4_hp.project  Vendor: spacex  Family: unknown
# Generated: 2026-09-25T16:38:01Z

f sym.imp.__deregister_frame_info 16 @ 0x6b520
f sym.imp.__register_frame_info 16 @ 0x6b530
f sym.imp.__cxa_finalize 16 @ 0x6b540
f sym.imp.__stack_chk_fail 16 @ 0x6b550
f sym.imp.memset 16 @ 0x6b560
f entry0 48 @ 0x6b570
f entry.fini0 96 @ 0x6b5dc
f entry.init0 48 @ 0x6b63c
f sym.controlcode_get_file_coverage 8 @ 0x6cdd0
f sym.controlcode_set_trace_buffer 97924 @ 0x6cde0
f sym.controlcode_reset_storage 56 @ 0x6d0d0
f sym.controlcode_init_runtime 712 @ 0x6d110
f sym.controlcode_init_assignment_data 8 @ 0x6d3e0
f sym.controlcode_execute 4536 @ 0x83280
