# Auto-generated by corpus_commit.py from e20c371cb7eed9ab
# Binary: user_v4_2beam.project  Vendor: spacex  Family: unknown
# Generated: 2026-09-25T16:38:07Z

f sym.imp.__deregister_frame_info 16 @ 0x6e4a0
f sym.imp.__register_frame_info 16 @ 0x6e4b0
f sym.imp.__cxa_finalize 16 @ 0x6e4c0
f sym.imp.__stack_chk_fail 16 @ 0x6e4d0
f sym.imp.memset 16 @ 0x6e4e0
f entry0 48 @ 0x6e4f0
f entry.fini0 96 @ 0x6e55c
f entry.init0 48 @ 0x6e5bc
f sym.controlcode_get_file_coverage 8 @ 0x72180
f sym.controlcode_set_trace_buffer 93172 @ 0x72190
f sym.controlcode_reset_storage 56 @ 0x72490
f sym.controlcode_init_runtime 712 @ 0x724d0
f sym.controlcode_init_assignment_data 8 @ 0x727a0
f sym.controlcode_execute 4536 @ 0x873a0
