# Auto-generated by corpus_commit.py from 907c24c2ecc48902
# Binary: ipcTask  Vendor: netgear  Family: unknown
# Generated: 2026-05-16T17:10:20Z

f main 0 @ 0x10b84
f sym._syscmd 0 @ 0x10d94
f sym.ipcRespondBack 0 @ 0x10e8c
f sym.ipcThreadInit 0 @ 0x10ec8
f sym.receivedTLV202 0 @ 0x10fb0
f sym.start_docsis_dhcp_server 0 @ 0x1108c
f sym.receivedCmOperational 0 @ 0x11188
f sym.ipcThread 0 @ 0x112bc
f sym.mfgLinkCheck_CBR750 0 @ 0x11644
f sym.usage 0 @ 0x11680
