# P3C_m0700.r2 — DJI Phantom 3 Professional / Standard Wi-Fi Module clisrv
# Firmware version: v01.00.2318 (m0700)
# Binary: clisrv (TCP socket server, DUPC 0x55 protocol dispatcher)
# Architecture: MIPS32 Big-Endian, uClibc 0.9.33.2
#
# Generated by: corpus_commit.py (seed entry — ongoing additions are automatic)
# Reference:    skel/.local/share/radare2/docs/protocols/dji-dupc-0x55.md
#
# Usage: loaded automatically by dji-wifi.r2 profile when symbols exist,
#        or manually: . symbols/dji/wifi/P3C_m0700.r2

# ── Network / socket layer ────────────────────────────────────────────────────
f clisrv.main                 2048 @ 0x407548
f clisrv.start_sock_server     896 @ 0x4024c8

# ── Protocol parsing ──────────────────────────────────────────────────────────
f clisrv.packet_parser        1968 @ 0x402fd0
f clisrv.cmd_dispatch          724 @ 0x406318

# ── Command handlers ──────────────────────────────────────────────────────────
f clisrv.wifi_cmd_handler     6120 @ 0x404b30
f clisrv.fw_flash             1876 @ 0x4041dc

# ── CRC functions ─────────────────────────────────────────────────────────────
f clisrv.crc8                  156 @ 0x401ab0
f clisrv.crc16                 280 @ 0x401b4c

# ── Data / tables ─────────────────────────────────────────────────────────────
f data.crc8_table              256 @ 0x419030
f data.crc16_table            1024 @ 0x419130
f data.cmd_jump_table          428 @ 0x4085c8
